# -*- coding: utf-8 -*-
"""chatter_time.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIieiyW-kzNHnnzM68G9TIxQS0VHPd_z
"""

from google.colab import drive 
drive.mount('drive', force_remount = False)

import pandas as pd
from scipy.io import loadmat

def create_csv(path):
  data = loadmat(path)
  df = pd.DataFrame(data['tsDS'], columns = ['time', 'acc_x'])
  return df

"""#2.0 inch stickout distance"""

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_320_005.mat"
df_2p0_c_320_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_425_020.mat"
df_2p0_c_425_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_425_025.mat"
df_2p0_c_425_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_570_001.mat"
df_2p0_c_570_001 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_570_002.mat"
df_2p0_c_570_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_570_005.mat"
df_2p0_c_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_570_010.mat"
df_2p0_c_570_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_770_001.mat"
df_2p0_c_770_001 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_770_002.mat"
df_2p0_c_770_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_770_002_2.mat"
df_2p0_c_770_002_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_770_005.mat"
df_2p0_c_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/c_770_010.mat"
df_2p0_c_770_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_320_005.mat"
df_2p0_i_320_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_320_010.mat"
df_2p0_i_320_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_425_020.mat"
df_2p0_i_425_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_425_025.mat"
df_2p0_i_425_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_570_002.mat"
df_2p0_i_570_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_570_005.mat"
df_2p0_i_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_570_010.mat"
df_2p0_i_570_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/i_770_001.mat"
df_2p0_i_770_001 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_005.mat"
df_2p0_s_320_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_010.mat"
df_2p0_s_320_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_015.mat"
df_2p0_s_320_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_020.mat"
df_2p0_s_320_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_020_2.mat"
df_2p0_s_320_020_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_025.mat"
df_2p0_s_320_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_030.mat"
df_2p0_s_320_030 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_035.mat"
df_2p0_s_320_035 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_040.mat"
df_2p0_s_320_040 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_045.mat"
df_2p0_s_320_045 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_050.mat"
df_2p0_s_320_050 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_320_050_2.mat"
df_2p0_s_320_050_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_425_005.mat"
df_2p0_s_425_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_425_010.mat"
df_2p0_s_425_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_425_015.mat"
df_2p0_s_425_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_425_017.mat"
df_2p0_s_425_017 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_425_020.mat"
df_2p0_s_425_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_570_002.mat"
df_2p0_s_570_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/s_570_005.mat"
df_2p0_s_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_320_005.mat"
df_2p0_u_320_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_320_010.mat"
df_2p0_u_320_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_320_020.mat"
df_2p0_u_320_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_320_050.mat"
df_2p0_u_320_050 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_425_017.mat"
df_2p0_u_425_017 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_425_017_2.mat"
df_2p0_u_425_017_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_425_020.mat"
df_2p0_u_425_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_570_002.mat"
df_2p0_u_570_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_570_005.mat"
df_2p0_u_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2inch_stickout/u_770_002.mat"
df_2p0_u_770_002 = create_csv(path)

"""# 2.5 inch stickout distance

"""

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/c_570_014.mat"
df_2p5_c_570_014 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/c_570_015s.mat"
df_2p5_c_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/c_770_005.mat"
df_2p5_c_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/i_570_012.mat"
df_2p5_i_570_012 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/i_570_014.mat"
df_2p5_i_570_014 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/i_570_015s.mat"
df_2p5_i_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/i_770_005.mat"
df_2p5_i_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_003.mat"
df_2p5_s_570_003 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_005.mat"
df_2p5_s_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_005_2.mat"
df_2p5_s_570_005_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_008.mat"
df_2p5_s_570_008 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_010.mat"
df_2p5_s_570_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_015.mat"
df_2p5_s_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_570_015_2.mat"
df_2p5_s_570_015_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_770_002.mat"
df_2p5_s_770_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/s_770_005.mat"
df_2p5_s_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_005.mat"
df_2p5_u_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_005_2.mat"
df_2p5_u_570_005_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_015.mat"
df_2p5_u_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_015_2.mat"
df_2p5_u_570_015_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_015_3.mat"
df_2p5_u_570_015_3 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_570_015_4.mat"
df_2p5_u_570_015_4 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/2p5inch_stickout/u_770_002.mat"
df_2p5_u_770_002 = create_csv(path)

"""# 3.5 inch stickout distance"""

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/c_1030_002.mat"
df_3p5_c_1030_002 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/c_770_015.mat"
df_3p5_c_770_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/i_770_010.mat"
df_3p5_i_770_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/i_770_010_2.mat"
df_3p5_i_770_010_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/i_770_015.mat"
df_3p5_i_770_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_570_015.mat"
df_3p5_s_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_570_025.mat"
df_3p5_s_570_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_570_025_2.mat"
df_3p5_s_570_025_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_570_030.mat"
df_3p5_s_570_030 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_770_005.mat"
df_3p5_s_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_770_008.mat"
df_3p5_s_770_008 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_770_010.mat"
df_3p5_s_770_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_770_010_2.mat"
df_3p5_s_770_010_2 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/s_770_015.mat"
df_3p5_s_770_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/u_570_015.mat"
df_3p5_u_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/u_570_025.mat"
df_3p5_u_570_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/u_570_030.mat"
df_3p5_u_570_030 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/u_770_005.mat"
df_3p5_u_770_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/3p5inch_stickout/u_770_015.mat"
df_3p5_u_770_015 = create_csv(path)

"""# 4.5 inch stickout distance"""

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/c_1030_010.mat"
df_4p5_c_1030_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/c_1030_015.mat"
df_4p5_c_1030_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/c_1030_016.mat"
df_4p5_c_1030_016 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/c_570_035.mat"
df_4p5_c_570_035 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/c_570_040.mat"
df_4p5_c_570_040 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/i_1030_010.mat"
df_4p5_i_1030_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/i_1030_012.mat"
df_4p5_i_1030_012 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/i_1030_013.mat"
df_4p5_i_1030_013 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/i_1030_014.mat"
df_4p5_i_1030_014 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_1030_005.mat"
df_4p5_s_1030_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_1030_007.mat"
df_4p5_s_1030_007 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_1030_013.mat"
df_4p5_s_1030_013 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_1030_014.mat"
df_4p5_s_1030_014 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_005.mat"
df_4p5_s_570_005 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_010.mat"
df_4p5_s_570_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_015.mat"
df_4p5_s_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_025.mat"
df_4p5_s_570_025 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_035.mat"
df_4p5_s_570_035 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_570_040.mat"
df_4p5_s_570_040 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_770_010.mat"
df_4p5_s_770_010 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_770_015.mat"
df_4p5_s_770_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/s_770_020.mat"
df_4p5_s_770_020 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/u_570_015.mat"
df_4p5_u_570_015 = create_csv(path)

path = "drive/MyDrive/cutting_tests_processed/4p5inch_stickout/u_570_040.mat"
df_4p5_u_570_040 = create_csv(path)

df_2p0_list = [df_2p0_c_320_005, df_2p0_c_425_020, df_2p0_c_425_025, df_2p0_c_570_001, df_2p0_c_570_002,
               df_2p0_c_570_005, df_2p0_c_570_010, df_2p0_c_770_001, df_2p0_c_770_002, df_2p0_c_770_002_2,
                df_2p0_c_770_005, df_2p0_c_770_010 , df_2p0_i_320_005, df_2p0_i_320_010, df_2p0_i_425_020,
               df_2p0_i_425_025, df_2p0_i_570_002, df_2p0_i_570_005, df_2p0_i_570_010, df_2p0_i_770_001,
              df_2p0_s_320_005, df_2p0_s_320_010, df_2p0_s_320_015, df_2p0_s_320_020, df_2p0_s_320_020_2,
               df_2p0_s_320_025, df_2p0_s_320_030, df_2p0_s_320_035, df_2p0_s_320_040, df_2p0_s_320_045,
                df_2p0_s_320_050, df_2p0_s_320_050_2, df_2p0_s_425_005, df_2p0_s_425_010, df_2p0_s_425_015,
               df_2p0_s_425_017, df_2p0_s_425_020, df_2p0_s_570_002, df_2p0_s_570_005, df_2p0_u_320_005,
                df_2p0_u_320_010, df_2p0_u_320_020, df_2p0_u_320_050, df_2p0_u_425_017, df_2p0_u_425_017_2,
               df_2p0_u_425_020, df_2p0_u_570_002, df_2p0_u_570_005, df_2p0_u_770_002]


df_2p5_list = [df_2p5_c_570_014, df_2p5_c_570_015, df_2p5_c_770_005, df_2p5_i_570_012, df_2p5_i_570_014,
               df_2p5_i_570_015, df_2p5_i_770_005, df_2p5_s_570_003, df_2p5_s_570_005, df_2p5_s_570_005_2,
               df_2p5_s_570_008, df_2p5_s_570_010, df_2p5_s_570_015, df_2p5_s_570_015_2, df_2p5_s_770_002,
               df_2p5_s_770_005, df_2p5_u_570_005, df_2p5_u_570_005_2, df_2p5_u_570_015, df_2p5_u_570_015_2,
               df_2p5_u_570_015_3, df_2p5_u_570_015_4, df_2p5_u_770_002]

df_3p5_list = [df_3p5_c_1030_002, df_3p5_c_770_015, df_3p5_i_770_010, df_3p5_i_770_010_2, df_3p5_i_770_015,
               df_3p5_s_570_015, df_3p5_s_570_025, df_3p5_s_570_025_2, df_3p5_s_570_030, df_3p5_s_770_005,
               df_3p5_s_770_008, df_3p5_s_770_010, df_3p5_s_770_010_2, df_3p5_s_770_015, df_3p5_u_570_015,
               df_3p5_u_570_025, df_3p5_u_570_030, df_3p5_u_770_005, df_3p5_u_770_015]


df_4p5_list = [df_4p5_c_1030_010, df_4p5_c_1030_015, df_4p5_c_1030_016, df_4p5_c_570_035, df_4p5_c_570_040, df_4p5_i_1030_010, df_4p5_i_1030_012,
               df_4p5_i_1030_013, df_4p5_i_1030_014, df_4p5_s_1030_005, df_4p5_s_1030_007, df_4p5_s_1030_013, df_4p5_s_1030_014, df_4p5_s_570_005,
                df_4p5_s_570_010, df_4p5_s_570_015, df_4p5_s_570_025, df_4p5_s_570_035, df_4p5_s_570_040, df_4p5_s_770_010,
               df_4p5_s_770_015, df_4p5_s_770_020, df_4p5_u_570_015, df_4p5_u_570_040]

def func(df, num):
  time_list = []
  start_time = df.iloc[0,0]
  end_time = df.iloc[-1,0]
  time_list.append(num)
  time_list.append(start_time)
  time_list.append(end_time)
  time_list.append(end_time - start_time)
  return time_list

def df_time_func(df_list, num):
  time_list = []
  for i in range(len(df_list)):
    lis = func(df_list[i], num)
    time_list.append(lis)
  return time_list

time_list = df_time_func(df_2p0_list, 0)

time_list += df_time_func(df_2p5_list, 1)

time_list += df_time_func(df_3p5_list, 2)

time_list += df_time_func(df_4p5_list, 3)

time_list

df = pd.DataFrame(time_list, columns = ['stick_out_distance', 'start_time', 'end_time', 'duration'])

df

len(df_2p0_list) + len(df_2p5_list) + len(df_3p5_list) + len(df_4p5_list)

df.to_csv("time_analysis.csv", index = False)

len(df_2p0_list)

len(df_2p5_list)

len(df_3p5_list)

len(df_4p5_list)

