# -*- coding: utf-8 -*-
"""Permutation_Entropy_PLOTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2MixuhS6NYkdgmll7KFWhqcH4rcHpTa

# 1 Window = 100 milliseconds approx
"""

from google.colab import drive 
drive.mount('drive', force_remount = False)

pip install ordpy

import pandas as pd
import numpy as np
import time
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from scipy.io import loadmat
from sklearn.model_selection import train_test_split
import scipy
from sklearn import preprocessing
import random
import ordpy
from scipy import signal

font = {
  'weight':'bold',
  'size' : 22 
}
plt.rc('font', **font)

def create_csv(path):
  data = loadmat(path)
  time_list = []
  for i in range(len(data['t'])):
    for j in data['t'][i]:
      time_list.append(j)
  acc_list = []
  for i in range(len(data['d'])):
    acc_list.append(data['d'][i][4])
  df = pd.DataFrame({'time':time_list,'acc_x':acc_list})
  return df

def resample_acc_x (acc_list):
  i = 0
  j = 16
  avg_acc_list = []
  while(j<len(acc_list)):
    sum = 0
    count = 0
    for k in range(i,j):
      sum += acc_list[k]
      count += 1
    avg = sum/count
    avg_acc_list.append(avg)
    i += 16
    j += 16
  sum = 0
  count = 0
  for k in range(i, len(acc_list)):
    sum += acc_list[k];
    count += 1
  
  avg = sum/count
  avg_acc_list.append(avg)
  time_list = []
  i = 0
  count = 0
  while(count<len(avg_acc_list)):
    time_list.append(i)
    i += (1/10000)
    count += 1
  df = pd.DataFrame({'time':time_list, 'acc_x':avg_acc_list})
  return df

def plot(df, ti):
  plt.figure(figsize = (110, 30))
  plt.plot(df.time, df.acc_x)
  plt.xlabel('time')
  plt.ylabel('acceleration_x')
  plt.savefig(ti)
  plt.show()

def data_func(path, ti):
  df = create_csv(path)
  acc_x_list = df.acc_x.tolist()

  ######## for filtering the data #################################

  sos = signal.butter(100, 1/16, 'low', analog = False, output = 'sos')
  filtered = signal.sosfilt(sos, acc_x_list)
  filtered = filtered.tolist()

  ######### for resampling of data  ###############################
  df = resample_acc_x(filtered)
  acc_x_list = df.acc_x.tolist()
  #################################################################

  plot(df, ti)
  return df, acc_x_list

"""# Overlapping Window of size 1024"""

def helper_func(x):
  i = 0
  j = 1024
  sublist = []
  while (j<=len(x)):
    lis = x[i:j]
    sublist.append(lis)
    i+=1
    j+=1
  return sublist

def func_overlap(acc_x_list):
  i = 0
  j = 50000
  lis = []
  while(j<=len(acc_x_list)):
    x = acc_x_list[i:j]
    lis += helper_func(x)
    i = j - 1023
    j = i + 50000
  x = acc_x_list[i:len(acc_x_list)]
  lis += helper_func(x)
  return lis

def per_ent_ov(lis):
  permutation_entropy_list = []
  for i in range(len(lis)):
    val = ordpy.permutation_entropy(lis[i], dx = 5)
    permutation_entropy_list.append(val)
  return permutation_entropy_list

"""# Not Overlapping Window of size 1024"""

def per_ent_nov(acc_x_list):
  permutation_entropy_list = []
  i = 0
  j = 1024
  time_count = 0
  while(j<len(acc_x_list)):
    t_start = time.time()
    val = ordpy.permutation_entropy(acc_x_list[i:j], dx = 5)
    t_end = time.time()
    time_count+=(t_end - t_start)
    permutation_entropy_list.append(val)
    i = j
    j+= 1024
  time_elapsed = time_count/len(permutation_entropy_list)
  print("The time taken to calculate the value of permutation entropy for a window of size 1024 samples within a time-span of 100 microseconds is {} seconds".format(time_elapsed))
  return permutation_entropy_list

def index_list_func(permutation_entropy_list):
  window_list = []
  for i in range(len(permutation_entropy_list)):
    window_list.append(i)
  return window_list

def plot_ov(permutation_entropy_list, window_list, st, ti):
  plt.figure(figsize = (150, 50))
  plt.plot(window_list, permutation_entropy_list, linewidth = 5)
  plt.title(st)
  # zip joins x and y coordinates in pairs
  for x,y in zip(window_list, permutation_entropy_list):
    label = "{},{:.2f}".format(x,y)
    plt.annotate(label, # this is the text
                 (x,y), # this is the point to label
                 textcoords="offset points", # how to position the text
                 xytext=(0,10), # distance from text to points (x,y)
                 ha='center') # horizontal alignment can be left, right or center
  plt.xlabel('Windows', fontsize = 30)
  plt.ylabel('Permutation_Entropy', fontsize = 30)
  plt.savefig(ti)
  plt.show()

def permutation_entropy_cal_and_plot_from_raw_for_overlapping(acc_x_list):
  lis = func_overlap(acc_x_list)
  permutation_entropy_list = per_ent_ov(lis)
  return permutation_entropy_list

def permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list):
  permutation_entropy_list = per_ent_nov(acc_x_list)
  return permutation_entropy_list

"""# time to frequency conversion"""

def time_2_freq_conversion(df, ti):
    Fx = np.array(df.acc_x)
    X = scipy.fft.fft(Fx)
    N = len(X)
    n = np.arange(N)
    sr = 1 / (10000)
    T = N/sr
    freq = n/T 

    # Get the one-sided specturm
    n_oneside = N//2
    # get the one side frequency
    f_oneside = freq[:n_oneside]

    plt.figure(figsize = (60, 10))
    plt.plot(f_oneside, np.abs(X[:n_oneside]), 'b')
    # plt.xlim(0, 1*(1e-5))
    plt.ylim(0, 450)
    st = "Frequency_"
    st+="acc_x"
    st+=" (Hz)"
    plt.xlabel(st)
    st = "FFT Amplitude |"
    st+= "acc_x"
    st+="(freq)|"
    plt.ylabel(st)
    plt.savefig(ti)
    plt.show()

"""# Power Spectral Density


"""

def psd(acc_x_list):
  input_length = len(acc_x_list)
  f_w_mean, ps_w_mean = signal.welch(acc_x_list, fs = 10000, nfft = 1024)
  f_w_median, ps_w_median = signal.welch(acc_x_list, fs = 10000, average = "median", nfft = 1024)
  freq, time, spectrogram = signal.spectrogram(np.array(acc_x_list), fs = 10000, nperseg = 1024)

  fig, ax = plt.subplots(4, 2, figsize = (20,20), constrained_layout = True)

  ax[0,0].psd(acc_x_list, NFFT = 1024, Fs = 10000)
  ax[0,0].set_title('Matplotlib_psd_using_welch_avg_periodogram')

  magnitude_spectrum, freq_1, line = ax[0,1].magnitude_spectrum(acc_x_list, Fs = 10000)
  ax[0,1].set_title('Matplotlib_magnitude_spectrum')

  ax[1,0].semilogy(f_w_mean, ps_w_mean, label = "mean")
  ax[1,0].semilogy(f_w_median, ps_w_median, label = "median")
  ax[1,0].set_title('Scipy_psd_using_welch')
  ax[1,0].set_xlabel('frequency [Hz]')
  ax[1,0].set_ylabel('PSD [V**2/Hz]')
  ax[1,0].legend(loc = "upper right")

  ax[1,1].magnitude_spectrum(acc_x_list, Fs = 10000, scale = "dB")
  ax[1,1].set_title('Matplotlib_log_magnitude_spectrum')

  ax[2,0].angle_spectrum(acc_x_list, Fs = 10000)
  ax[2,0].set_title("Angle_spectrum")

  ax[2,1].phase_spectrum(acc_x_list, Fs = 10000)
  ax[2,1].set_title("Phase_spectrum")

  spectrum, fre, tim, im = ax[3,0].specgram(acc_x_list, Fs = 10000, NFFT = 1024)
  ax[3,0].set_title("Matplotlib_spectrogram")
  ax[3,0].set_ylabel('Frequency [Hz]')
  ax[3,0].set_xlabel('Time [sec]')
  
  ax[3,1].pcolormesh(time, freq, spectrogram, cmap = "YlOrRd")
  ax[3,1].set_title('Scipy_spectrogram')
  ax[3,1].set_ylabel('Frequency [Hz]')
  ax[3,1].set_xlabel('Time [sec]')
  #fig.tight_layout

"""---
#2 inches stickout distance


---

# Cutting speed = 320 rpm, DOC = 0.005 inches
"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_005.png")

"""# Cutting speed = 320 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_010.png")

"""# Cutting speed = 320 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_015.png")

"""# Cutting speed = 320 rpm, DOC = 0.020 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p020.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_020.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_020.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_020.png")

"""# Cutting speed = 320 rpm, DOC = 0.025 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p025.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_025.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_025.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_025.png")

"""# Cutting speed = 320 rpm, DOC = 0.030 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p030.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_030.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_030.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_030.png")

"""# Cutting speed = 320 rpm, DOC = 0.050 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p050.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_050.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_050.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_050.png")

"""# Cutting speed = 320 rpm, DOC = 0.060 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm320_doc0p060_xAccDetached.mat"
ti = "time_domain_plot_for_resampled_data_rpm_320_doc_060.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_320_doc_060.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_320_doc_060.png")

"""# Cutting speed = 425 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_005.png")

"""# Cutting speed = 425 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_010.png")

"""# Cutting speed = 425 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_015.png")

"""# Cutting speed = 425 rpm, DOC = 0.017 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p017.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_017.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_017.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_017.png")

"""# Cutting speed = 425 rpm, DOC = 0.020 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p020.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_020.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_020.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_020.png")

"""# Cutting speed = 425 rpm, DOC = 0.025 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm425_doc0p025.mat"
ti = "time_domain_plot_for_resampled_data_rpm_425_doc_025.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_425_doc_025.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_425_doc_025.png")

"""# Cutting speed = 570 rpm, DOC = 0.001 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm570_doc0p001.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_001.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_001.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_001.png")

"""# Cutting speed = 570 rpm, DOC = 0.002 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm570_doc0p002.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_002.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_002.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_002.png")

"""# Cutting speed = 570 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm570_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_005.png")

"""# Cutting speed = 570 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm570_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_010.png")

"""# Cutting speed = 770 rpm, DOC = 0.001 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm770_doc0p001.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_001.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_001.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_001.png")

"""# Cutting speed = 770 rpm, DOC = 0.002 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm770_doc0p002.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_002.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_002.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_002.png")

"""# Cutting speed = 1030 rpm, DOC = 0.001 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_rpm1030_doc0p001.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_001.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_001.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_001.png")

"""#Smoothing_cut_no_chatter


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2inchStickout/F_08-Jun-2017_smoothingCut2_noChatter.mat"
ti = "time_domain_plot_for_resampled_data_smoothing_cut_no_chatter.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_smoothing_cut_no_chatter.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_smoothing_cut_no_chatter.png")

"""---
#2.5 inches stickout distance


---

# Cutting speed = 570 rpm, DOC = 0.003 inches
"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p003.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_003.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_003.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_003.png")

"""# Cutting speed = 570 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_005.png")

"""# Cutting speed = 570 rpm, DOC = 0.008 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p008.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_008.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_008.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_008.png")

"""# Cutting speed = 570 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_010.png")

"""# Cutting speed = 570 rpm, DOC = 0.012 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p012.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_012.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_012.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_012.png")

"""# Cutting speed = 570 rpm, DOC = 0.014 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p014.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_014.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_014.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_014.png")

"""# Cutting speed = 570 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_015.png")

"""# Cutting speed = 570 rpm, DOC = 0.015 inches (trial 2)


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm570_doc0p015_trial2.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_015_trail2.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_015_trial2.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_015_trial2.png")

"""# Cutting speed = 770 rpm, DOC = 0.002 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm770_doc0p002.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_002.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_002.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_002.png")

"""# Cutting speed = 770 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_2p5inchStickout/F_12-Jun-2017_rpm770_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_005.png")

"""---
#3 inches stickout distance


---

# Cutting speed = 570 rpm, DOC = 0.015 inches
"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3inchStickout/F_12-Jun-2017_rpm570_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_015.png")

"""---
#3.5 inches stickout distance


---

# Cutting speed = 570 rpm, DOC = 0.015 inches
"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_12-Jun-2017_rpm570_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_015.png")

"""# Cutting speed = 570 rpm, DOC = 0.025 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_12-Jun-2017_rpm570_doc0p025.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_025.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_025.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_025.png")

"""# Cutting speed = 570 rpm, DOC = 0.030 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_12-Jun-2017_rpm570_doc0p030.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_030.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_030.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_030.png")

"""# Cutting speed = 770 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_14-Jun-2017_rpm770_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_005.png")

"""# Cutting speed = 770 rpm, DOC = 0.008 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_14-Jun-2017_rpm770_doc0p008.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_008.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_008.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_008.png")

"""# Cutting speed = 770 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_14-Jun-2017_rpm770_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_010.png")

"""# Cutting speed = 770 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_14-Jun-2017_rpm770_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_015.png")

"""# Cutting speed = 1030 rpm, DOC = 0.002 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_3p5inchStickout/F_14-Jun-2017_rpm1030_doc0p002.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_002.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_002.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_002.png")

"""---
#4.5 inches stickout distance


---

# Cutting speed = 570 rpm, DOC = 0.005 inches
"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_005.png")

"""# Cutting speed = 570 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_010.png")

"""# Cutting speed = 570 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_015.png")

"""# Cutting speed = 570 rpm, DOC = 0.025 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p025.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_025.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_025.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_025.png")

"""# Cutting speed = 570 rpm, DOC = 0.035 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p035.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_035.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_035.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_035.png")

"""# Cutting speed = 570 rpm, DOC = 0.040 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_12-Jun-2017_rpm570_doc0p040.mat"
ti = "time_domain_plot_for_resampled_data_rpm_570_doc_040.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_570_doc_040.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_570_doc_040.png")

"""# Cutting speed = 770 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm770_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_010.png")

"""# Cutting speed = 770 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm770_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_015.png")

"""# Cutting speed = 770 rpm, DOC = 0.020 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm770_doc0p020.mat"
ti = "time_domain_plot_for_resampled_data_rpm_770_doc_020.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_770_doc_020.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_770_doc_020.png")

"""# Cutting speed = 1030 rpm, DOC = 0.005 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p005.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_005.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_005.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_005.png")

"""# Cutting speed = 1030 rpm, DOC = 0.007 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p007.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_007.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_007.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_007.png")

"""# Cutting speed = 1030 rpm, DOC = 0.010 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p010.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_010.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_010.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_010.png")

"""# Cutting speed = 1030 rpm, DOC = 0.012 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p012.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_012.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_012.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_012.png")

"""# Cutting speed = 1030 rpm, DOC = 0.013 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p013.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_013.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_013.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_013.png")

"""# Cutting speed = 1030 rpm, DOC = 0.014 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p014.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_014.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_014.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_014.png")

"""# Cutting speed = 1030 rpm, DOC = 0.015 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p015.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_015.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_015.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_015.png")

"""# Cutting speed = 1030 rpm, DOC = 0.016 inches


"""

path = "drive/MyDrive/cutting_tests_raw/timeSeries_4p5inchStickout/F_13-Jun-2017_rpm1030_doc0p016.mat"
ti = "time_domain_plot_for_resampled_data_rpm_1030_doc_016.png"
df, acc_x_list = data_func(path, ti)

permutation_entropy_list_non_overlapping = permutation_entropy_cal_and_plot_from_raw_for_non_overlapping(acc_x_list)
index_list = index_list_func(permutation_entropy_list_non_overlapping)

plot_ov(permutation_entropy_list_non_overlapping, index_list, "Plot for non-overlapping windows",  "Plot_for_non_overlapping_windows_for_resampled_data_rpm_1030_doc_016.png")

psd(acc_x_list)

time_2_freq_conversion(df, "plot_of_frequency_spectrum_for_resampled_data_rpm_1030_doc_016.png")

